### ISSUE TITLE
Ho to wire the raspberrypi

### ISSUE THREAD

**Issue by Robotechnic** [victorvorobev/NazaCanDecoder#2]
Hello, @victorvorobev, I am interested by your project and I want to use it to create autonomous drone with a raspberry pi 0. Can you tell me how to wire the raspberry pi?
I have a ca traceiver and a raspberry pi 0
Thanks

**Comment by viktorvorobev** [comment]
Hello!
Well, I can't actually answer to your question, since I don't know what CAN transceiver you use, but I guess there should be plenty of guides, e.g. [this one](https://www.beyondlogic.org/adding-can-controller-area-network-to-the-raspberry-pi/) for MCP2515 and RPi Zero.

**Comment by Robotechnic** [comment]
Ok thanks I didn't realize that
